pull_request_rules:
  # if there is a conflict in a backport PR, ping the author.
  - name: ping author on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please rebase it 🙏
