name: Databend Base
on:
  push:
    paths-ignore:
      - 'website/'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'website/'
      - '*.md'

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  lint_and_build:
    name: "Lint & Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./
          config_file: .yamllint.yml

      - name: Rust setup
        run: bash ./scripts/setup/dev_setup.sh

      - uses: ./.github/actions/cache-cargo-registry
        with:
          cache_reset_key: ${{ secrets.CACHE_RESET_KEY }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests -- -D warnings
        env:
          CARGO_INCREMENTAL: '0'

      - name: Check formating
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: '0'

      - name: Build
        run: cargo build --verbose
        env:
          CARGO_INCREMENTAL: '0'
