name: Audit Security

on:
  push:
    paths:
      - '**/Cargo.lock'
  pull_request:
    paths:
      - '**/Cargo.lock'
  schedule:
    - cron: '25 4 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  audit-security:
    name: Audit Security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip audit')"
    steps:
      - uses: actions/checkout@v2

      - name: Install cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit

      - name: Audit dependencies
        uses: actions-rs/cargo@v1
        with:
          command: audit
