name: Stateful(Standalone)
on:
  push:
    paths-ignore:
      - 'website/'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'website/'
      - '*.md'

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  build:
    name: "Tests"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # Linux (ubuntu-latest only)
          - { os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false }
    steps:
      - uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh -o -t

      - uses: ./.github/actions/cache-cargo-registry
        with:
          cache_reset_key: ${{ secrets.CACHE_RESET_KEY }}

      - name: Build
        run: cargo build --verbose
        env:
          CARGO_INCREMENTAL: '0'

      - name: Minio Setup for (ubuntu-latest only)
        run: |
          docker run -d -p 9900:9000 --name minio \
                  -e "MINIO_ACCESS_KEY=minioadmin" \
                  -e "MINIO_SECRET_KEY=minioadmin" \
                  -v /tmp/data:/data \
                  -v /tmp/config:/root/.minio \
                  minio/minio server /data

          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_EC2_METADATA_DISABLED=true
          aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://testbucket
          aws --endpoint-url http://127.0.0.1:9900/ s3 cp tests/data s3://testbucket/tests/data  --recursive


      - name: Run Stateless Tests with Standalone mode (ubuntu-latest only)
        run: |
          bash ./scripts/ci/ci-run-stateful-tests-standalone-s3.sh
