name: Stateless(Cluster)
on:
  push:
    paths-ignore:
      - 'website/'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'website/'
      - '*.md'

env:
  CARGO_TERM_COLOR: always
  PROTOC: protoc

jobs:
  build:
    name: "Tests"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          # Linux
          - { os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false }
          # Macos
          - { os: macos-latest, toolchain: stable, target: x86_64-apple-darwin, cross: false }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh -o -t

      - uses: ./.github/actions/cache-cargo-registry
        with:
          cache_reset_key: ${{ secrets.CACHE_RESET_KEY }}

      - name: Build
        run: cargo build --verbose
        env:
          CARGO_INCREMENTAL: '0'

      - name: Run Stateless Tests with Cluster mode
        run: |
          bash ./scripts/ci/ci-run-stateless-tests-cluster.sh
